name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linters
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    # Uncomment when you have tests set up
    # - name: Run tests
    #   run: npm test

    # Add deployment steps here when ready
    # - name: Deploy to production
    #   if: github.ref == 'refs/heads/main' && matrix.node-version == '18.x'
    #   run: echo "Add deployment commands here"
